RIACC/RIACC/Models/DealerUIViewEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RIACC.Entity;

namespace RIACC.Models
{
    public class DealerUIViewEntity: Dealer
    {
        public IList<DealerLocation> LocationList { get; set; }
    }
}

RIACC/RIACC/Models/PurchaseOrderUIViewEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RIACC.Entity;

namespace RIACC.Models
{
    public class PurchaseOrderUIViewEntity : PurchaseOrder
    {        
        public IList<PurchaseOrderDetail> PODetailsList { get; set; }
    }
}

RIACC/RIACC/Models/UserUIViewEntity.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using RIACC.Entity;

namespace RIACC.Models
{
    public class UserUIViewEntity : User
    {

    }
}

RIACC/RIACC/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class AdminController : Controller
    {
        //
        // GET: /Admin/

        public ActionResult Home()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/DPComponentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class DPComponentController : Controller
    {
        //
        // GET: /DPComponent/

        public ActionResult DPComponent()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/DealerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class DealerController : Controller
    {
        //
        // GET: /Dealer/

        public ActionResult Dealer()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/DeliveryOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class DeliveryOrderController : Controller
    {
        //
        // GET: /DeliveryOrder/

        public ActionResult DeliveryOrder()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Home()
        {
            ModelState.AddModelError("Test", "Invalid user/Password");
            return View();
        }

        public ActionResult About()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/LocationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class LocationController : Controller
    {
        //
        // GET: /Location/

        public ActionResult Location()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/PurchaseOrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class PurchaseOrderController : Controller
    {
        //
        // GET: /PurchaseOrder/

        public ActionResult PurchaseOrder()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/StaffController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class StaffController : Controller
    {
        //
        // GET: /Staff/

        public ActionResult Home()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class SupplierController : Controller
    {
        //
        // GET: /Supplier/

        public ActionResult Supplier()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/TrackListController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class TrackListController : Controller
    {
        //
        // GET: /TrackList/

        public ActionResult TrackList()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/UnitController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class UnitController : Controller
    {
        //
        // GET: /Unit/

        public ActionResult Unit()
        {
            return View();
        }

    }
}

RIACC/RIACC/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace RIACC.Controllers
{
    public class UserController : Controller
    {
        //
        // GET: /User/

        public ActionResult User()
        {
            return View();
        }

    }
}

RIACC/RIACC/Views/Admin/Home.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
    ViewBag.Title = "Admin - Home";
    ViewBag.CurrentPage = "home";
}

RIACC/RIACC/Views/DPComponent/DPComponent.cshtml
@{
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
    ViewBag.Title = "Staff - DP Component";
    ViewBag.CurrentPage = "dp-component";
}

<h2>DPComponent</h2>

RIACC/RIACC/Views/DeliveryOrder/DeliveryOrder.cshtml
@{
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
    ViewBag.Title = "Staff - Delivery Order";
    ViewBag.CurrentPage = "delivery-order";
}

<h2>DeliveryOrder</h2>

RIACC/RIACC/Views/Home/About.cshtml
@{
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
    ViewBag.Title = "About Us";
    ViewBag.CurrentPage = "about";
}


<div class="container">
    <h3 class="page-header">About Us</h3>
    <p>The RIACC - Application Name is made by the ARMED Software Development company to blah, blah, blah, blah and blah!</p>

    <p><strong>Below are the developer's names:</strong></p>
    <ol class="developers">
        <li>Mark Oliver 'KornyMan' Tan</li>
        <li>Edward Joseph 'Farty Boy' Mabuyo</li>
        <li>Rob 'Booby Boy' Roxas</li>
    </ol>
</div>

RIACC/RIACC/Views/Home/Home.cshtml
@{
    Layout = "~/Views/Shared/_DefaultLayout.cshtml";
    ViewBag.Title = "Home";
    ViewBag.CurrentPage = "home";
}

<div class="container">
@using (Html.BeginForm("Login", "User"))
{
    <h4 class="page-header">Sign In</h4>
    @Html.ValidationSummary()
    <div class="col-md-1">
        <div class="icon-login"></div>
    </div>
    <div class="col-md-3">
        <div class="form-group">
            <label for="username">User Name</label>
            <input type="text" class="form-control" id="username" placeholder="Enter Username" />
        </div>
        <div class="form-group">
            <label for="password">Password</label>
            <input type="text" class="form-control" id="password" placeholder="Enter Password" />
        </div>
        <div class="text-right">
            <input type="submit" class="btn btn-default" value="Sign In"/>
        </div>
    </div>
} 
</div>

RIACC/RIACC/Views/PurchaseOrder/PurchaseOrder.cshtml
@{
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
    ViewBag.Title = "Staff - Purchase Order";
    ViewBag.CurrentPage = "purchase-order";
}

<h2>PurchaseOrder</h2>

<link rel="stylesheet" href="@Url.Content("~/Content/kendo.common.min.css")">
<link rel="stylesheet" href="@Url.Content("~/Content/kendo.default.min.css")">
<script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
<script src="@Url.Content("~/Scripts/kendo.web.min.js")"></script>
<script src="@Url.Content("~/Scripts/kendo.aspnetmvc.min.js")"></script>

@model RIACC.Models.PurchaseOrderUIViewEntity


@Html.Kendo().AutoCompleteFor(m => m.PONumber).Placeholder("Password")

RIACC/RIACC/Views/Shared/EditorTemplates/Currency.cshtml
@model decimal?

@(Html.Kendo().CurrencyTextBoxFor(m => m)      
      .HtmlAttributes(new {style="width:100%"})
      .Min(0)
)

RIACC/RIACC/Views/Shared/EditorTemplates/Date.cshtml
@model DateTime?

@(Html.Kendo().DatePickerFor(m => m))

RIACC/RIACC/Views/Shared/EditorTemplates/DateTime.cshtml
@model DateTime?

@(Html.Kendo().DateTimePickerFor(m => m))

RIACC/RIACC/Views/Shared/EditorTemplates/Email.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox" })

RIACC/RIACC/Views/Shared/EditorTemplates/EmailAddress.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="email" })

RIACC/RIACC/Views/Shared/EditorTemplates/GridForeignKey.cshtml
@model object
           
@(
 Html.Kendo().DropDownListFor(m => m)        
        .BindTo((SelectList)ViewData[ViewData.TemplateInfo.GetFullHtmlFieldName("") + "_Data"])
)

RIACC/RIACC/Views/Shared/EditorTemplates/Integer.cshtml
@model int?

@(Html.Kendo().IntegerTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
      .Min(int.MinValue)
      .Max(int.MaxValue)
)

RIACC/RIACC/Views/Shared/EditorTemplates/Number.cshtml
@model double?

@(Html.Kendo().NumericTextBoxFor(m => m)
      .HtmlAttributes(new { style = "width:100%" })
)

RIACC/RIACC/Views/Shared/EditorTemplates/Password.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="password" })

RIACC/RIACC/Views/Shared/EditorTemplates/String.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox" })

RIACC/RIACC/Views/Shared/EditorTemplates/Time.cshtml
@model DateTime?
           
@(Html.Kendo().TimePickerFor(m => m))

RIACC/RIACC/Views/Shared/EditorTemplates/Url.cshtml
@model object 

@Html.TextBoxFor(model => model, new {@class="k-textbox", type="url" })

RIACC/RIACC/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/colorbox.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.common.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.default.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/jquery.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/kendo.all.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/kendo.aspnetmvc.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.colorbox-min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/riacc.js")" type="text/javascript"></script>

    @RenderSection("PageSpecificCss", false)
    @RenderSection("PageSpecificJs", false)
</head>

<body id="@ViewBag.CurrentPage">
    <div class="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">RIACC</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="@if (ViewBag.CurrentPage == "home") { @:active 
                }">@Html.ActionLink("Home", "Home", "Admin")</li>
                <li class="@if (ViewBag.CurrentPage == "user") { @:active 
                }">@Html.ActionLink("Manage Users", "User", "User")</li>
                <li class="@if (ViewBag.CurrentPage == "audit") { @:active 
                }">@Html.ActionLink("Audit Trail", "AuditTrail", "Admin")</li>
                <li class="@if (ViewBag.CurrentPage == "changepassword") { @:active 
                }">@Html.ActionLink("Change Password", "ChangePassword", "User")</li>
                <li>@Html.ActionLink("Log Out", "LogOut", "User")</li>
                <!--<li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Master Data <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li><a href="company/">Company</a></li>
                    <li><a href="gender/">Gender</a></li>
                    <li><a href="marital_status/">Marital Status</a></li>
                    <li class="divider"></li>
                    <li class="dropdown-header">Address</li>
                    <li><a href="city/">City</a></li>
                    <li><a href="province/">Province</a></li>
                    <li><a href="country/">Country</a></li>
                  </ul>
                </li>-->
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        @RenderBody()
    </div>
</body>
</html>

RIACC/RIACC/Views/Shared/_DefaultLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/colorbox.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.common.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.default.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/jquery.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/kendo.all.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/kendo.aspnetmvc.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.colorbox-min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/riacc.js")" type="text/javascript"></script>

    @RenderSection("PageSpecificCss", false)
    @RenderSection("PageSpecificJs", false)
</head>

<body id="@ViewBag.CurrentPage">
    <div class="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">RIACC</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="@if (ViewBag.CurrentPage == "home") { @:active 
                }">@Html.ActionLink("Sign In", "Home", "Home")</li>
                <li class="@if (ViewBag.CurrentPage == "about") { @:active 
                }">@Html.ActionLink("About", "About", "Home")</li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        @RenderBody()
    </div>
</body>
</html>

RIACC/RIACC/Views/Shared/_StaffLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/bootstrap.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/bootstrap-theme.min.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/colorbox.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.common.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.dataviz.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.default.min.css")" rel="stylesheet" type="text/css" />
	<link href="@Url.Content("~/Content/kendo/2013.2.918/kendo.dataviz.default.min.css")" rel="stylesheet" type="text/css" />
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/jquery.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/kendo.all.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo/2013.2.918/kendo.aspnetmvc.min.js")" type="text/javascript"></script>
	<script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery.colorbox-min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/riacc.js")" type="text/javascript"></script>

    @RenderSection("PageSpecificCss", false)
    @RenderSection("PageSpecificJs", false)
</head>

<body id="@ViewBag.CurrentPage">
    <div class="wrap">
        <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#">RIACC</a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="@if (ViewBag.CurrentPage == "home") { @:active 
                }">@Html.ActionLink("Home", "Home", "Staff")</li>
                <li class="dropdown @if(ViewBag.CurrentPage.IndexOf("master") > -1){ @:active
                }">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">Master Data <b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li class="@if(ViewBag.CurrentPage=="master-location"){ @:active
                    }">@Html.ActionLink("Location", "Location", "Location")</li>
                  </ul>
                </li>
                <li class="@if (ViewBag.CurrentPage == "purchase-order") { @:active 
                }">@Html.ActionLink("PO", "PurchaseOrder", "PurchaseOrder")</li>
                <li class="@if (ViewBag.CurrentPage == "delivery-order") { @:active 
                }">@Html.ActionLink("DO/DR", "DeliveryOrder", "DeliveryOrder")</li>
                <li class="@if (ViewBag.CurrentPage == "dp-component") { @:active 
                }">@Html.ActionLink("DP Component", "DPComponent", "DPComponent")</li>
                <li class="@if (ViewBag.CurrentPage == "track-list") { @:active 
                }">@Html.ActionLink("Track List", "TrackList", "TrackList")</li>
                <li class="@if (ViewBag.CurrentPage == "inventory-list") { @:active 
                }">@Html.ActionLink("Inventory List", "InventoryList", "InventoryList")</li>
                <li class="@if (ViewBag.CurrentPage == "changepassword") { @:active 
                }">@Html.ActionLink("Change Password", "ChangePassword", "User")</li>
                <li>@Html.ActionLink("Log Out", "LogOut", "User")</li>
              </ul>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        @RenderBody()
    </div>
</body>
</html>

RIACC/RIACC/Views/Staff/Home.cshtml
@{
    Layout = "~/Views/Shared/_StaffLayout.cshtml";
    ViewBag.Title = "Staff - Home";
    ViewBag.CurrentPage = "home";
}

RIACC/RIACC/Views/Supplier/Supplier.cshtml
@{
    ViewBag.Title = "Supplier";
}

<h2>Supplier</h2>

RIACC/RIACC/Views/Unit/Unit.cshtml
@{
    ViewBag.Title = "Unit";
}

<h2>Unit</h2>